---
title: "ARIMA model"
author: "Jiefeng Chen"
date: "3/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(forecast) 
library(ggplot2)
library(TSA)
library(readr)
library(lubridate)
library(plyr)

#import data:
pdx <- read.csv("https://www.wrh.noaa.gov/pqr/climate/Portland_dailyclimatedata.csv", skip = 6) #skip 6 rows before taking the first row as variable name
```


Import data and filter target variables
```{r}
#define replacing NA by its month average function
rmna.avg=function(rain.ts,rainfall_month){

        b=month.abb[cycle(rain.ts)]
        a=data.frame(b,rainfall_month)

        for (i in 1:length(a[,2])){
                if (is.na(a[i,2])){
                        month=a[i,1]
                        a[i,2]=mean(a[a[,1]==month,2], na.rm=TRUE)
        
           }
        }
        rainfall_month=a[,2]
        return(rainfall_month)
}

```

## Rains
```{r}
#consider only rain data, so we only need precipitation
pdx_rains <- pdx[pdx$X=="PR", ]

# pull out and clean up the amount of rain by month
rainfall_month <- pdx_rains$AVG.or.Total
rainfall_month <- gsub("M", NA, rainfall_month) #M is missing
rainfall_month <- gsub("T", 0, rainfall_month) #T is missing too, but they are close to 0 output, so I set T=0
rainfall_month <- as.numeric(rainfall_month)

# this is a time series we could work with
rain.ts <- ts(rainfall_month, start = c(1940,10),deltat = 1/12)

plot(rain.ts, main = "Portland, OR. Monthly Average Rainfall (1940-2019)",
     xlab = "Year",
     ylab = "Precipitation (in)")

# there are two missing values
table(is.na(rain.ts))
# replace NA by its month average 
rainfall_month=rmna.avg(rain.ts, rainfall_month)
rain.ts <- ts(rainfall_month, start = c(1940,10), deltat = 1/12)
table(is.na(rain.ts))

```
## set up training data as the data before 2005
```{r}
rain.ts.train=ts(rainfall_month, start = c(1940,10), end=c(2004,12),deltat = 1/12)
## extract time
t<- time(max_t_ts)
## create data frame of all variables
df<- data.frame(time = t, max_t = max_t_ts, min_t = min_t_ts, rain = rain.ts)

#length
L<-nrow(df)
 
## split df
tr<-1:(L-181)
train<- df[tr,]
test<- df[-tr,]
```

## ARIMA Model analysis
```{r}
#difference the data
rain.ts.diff=diff(rain.ts.train, lag=12)
rain.ts.diff=diff(rain.ts.diff, lag=12)
plot(rain.ts.diff)
```
```{r}
#ACF and PACF
par(mfrow=c(1,2))
acf(rain.ts.diff, lag.max=48, main='ACF')
pacf(rain.ts.diff,lag.max=48, main='PACF')
```

```{r}
# fit a SARIMA model
# 1 time difference
# seasonal lag 12 are zero out at ACF and PACF; so ARMA(1,1) model in seasonal. 
# non seasonal; ACF is cut off after lag1; but PACF is tail off. so it is MA(1)
# we will try ARIMA(0,1,1)x(1,1,1)12, ARIMA(1,1,1)x(0,1,1)12, ARIMA(0,1,2)x(0,1,1)12

(rain.fit1=arima(rain.ts.train, order=c(0,0,2), seasonal=list(order=c(0,1,1), period=12)))
(rain.fit2=arima(rain.ts.train, order=c(1,0,1), seasonal=list(order=c(0,1,1), period=12)))
(rain.fit3=arima(rain.ts.train, order=c(0,0,3), seasonal=list(order=c(0,1,2), period=12)))
(rain.fit4=arima(rain.ts.train, order=c(0,0,1), seasonal=list(order=c(0,1,1), period=12)))
#try ARIMA
(rain.fit4=arima(rain.ts.train, order=c(1,0,1), include.mean=F, method="ML"))
```
## SARIMA(0,0,1)x(0,1,1)12 model provide min AIC: 3048.69
## SARMIA(1,0,1)x(0,1,1)12 model provide close AIC 3050.19

```{r}
#checking if residual is white noise
tsdiag(rain.fit4)
tsdiag(rain.fit2)
qqnorm(rain.fit4$residuals)
qqline(rain.fit4$residuals)

res=rain.fit2$residuals
acf(res)
pacf(res)
```
it looks like rain.fit2 has better white noise residual. 


## predict and compare to the test data
```{r}
pred2=predict(rain.fit2, n.ahead=181)
pred4=predict(rain.fit4, n.ahead=181)
#plot the original data
plot(rain.ts, xlim=c(2005,2020), xlab='Rain Fall')
#adding the model prediction as red line; 95% confidence as blue line
lines(pred2$pred, col='red')
lines(pred2$pred-2*pred2$se, col='blue')
lines(pred2$pred+2*pred2$se, col='blue')
```

```{r}
# calculate MSE
rain.test<- ts(test$rain, start = 2005, frequency = 12)
trail2=pred2$pred
trail4=pred4$pred
mse2=sum((trail2-rain.test)^2, na.rm=TRUE)/181
mse4= sum((trail4-rain.test)^2, na.rm=TRUE)/181
mse2
mse4
```
MSE in ARMIA(1,0,1)x(0,1,1)12 model is much smaller. 


